src/Anduin.AnduinOSHome/Controllers/CultureController.cs
using Aiursoft.WebTools.Attributes;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace Anduin.AnduinOSHome.Controllers;

/// <summary>
/// This controller is used to change the current culture.
/// </summary>
[LimitPerMin]
public class CultureController : ControllerBase
{
    public IActionResult Set(string culture, string returnUrl)
    {
        if (string.IsNullOrEmpty(culture))
            return BadRequest("Culture cannot be null or empty.");

        Response.Cookies.Append(
            CookieRequestCultureProvider.DefaultCookieName,
            CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
            new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
        );

        if (!string.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
        {
            return LocalRedirect(returnUrl);
        }

        return RedirectToAction("Index", "Home");
    }
}

src/Anduin.AnduinOSHome/Views/Shared/Components/Footer/Default.cshtml
@using Microsoft.AspNetCore.Localization

@* Footer *@
<footer class="py-5 bg-dark">
    <div class="container">
        <div class="row mb-4">
            <div class="col-12 col-lg-4">
                <div class="mb-3">
                    <svg style="fill:white;" xmlns="http://www.w3.org/2000/svg"
                         xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="24px" height="24px"
                         viewBox="0 0 20 20" xml:space="preserve">
                        <path d="M19.4,4.1l-9-4C10.1,0,9.9,0,9.6,0.1l-9,4C0.2,4.2,0,4.6,0,5s0.2,0.8,0.6,0.9l9,4C9.7,10,9.9,10,10,10s0.3,0,0.4-0.1l9-4
              C19.8,5.8,20,5.4,20,5S19.8,4.2,19.4,4.1z" />
                        <path d="M10,15c-0.1,0-0.3,0-0.4-0.1l-9-4c-0.5-0.2-0.7-0.8-0.5-1.3c0.2-0.5,0.8-0.7,1.3-0.5l8.6,3.8l8.6-3.8c0.5-0.2,1.1,0,1.3,0.5
              c0.2,0.5,0,1.1-0.5,1.3l-9,4C10.3,15,10.1,15,10,15z" />
                        <path d="M10,20c-0.1,0-0.3,0-0.4-0.1l-9-4c-0.5-0.2-0.7-0.8-0.5-1.3c0.2-0.5,0.8-0.7,1.3-0.5l8.6,3.8l8.6-3.8c0.5-0.2,1.1,0,1.3,0.5
              c0.2,0.5,0,1.1-0.5,1.3l-9,4C10.3,20,10.1,20,10,20z" />
                    </svg>
                </div>
                <p class="text-white-50">
                    @Localizer["AnduinOS - a custom Ubuntu-based Linux distribution that offers a familiar and easy-to-use experience for anyone moving to Linux."]
                </p>
                <div class="dropdown mt-3 mb-3">
                    @{
                        var currentCulture = ViewContext.HttpContext.Features
                            .Get<IRequestCultureFeature>()?
                            .RequestCulture.Culture.Name;
                    }
                    <form asp-controller="Culture" asp-action="Set" method="post" class="d-inline" asp-route-returnUrl="@(Context.Request.Path + Context.Request.QueryString)">
                        <select name="culture" onchange="this.form.submit()" class="form-select form-select-sm w-auto">
                            @foreach (var culture in Aiursoft.WebTools.OfficialPlugins.LocalizationPlugin.SupportedCultures)
                            {
                                <option value="@culture.Key"
                                        selected="@(culture.Key == currentCulture ? "selected" : null)">
                                    @culture.Value
                                </option>
                            }
                        </select>
                    </form>
                </div>
            </div>
            <div class="col-12 col-md-4 col-lg-2 mb-3 mb-md-0">
                <h4 class="text-light fs-5">@Localizer["Resources"]</h4>
                <ul class="list-unstyled ps-0 mb-0 mt-3">
                    <li class="mt-2">
                        <a href="https://news.anduinos.com" class="text-white-50">@Localizer["News"]</a>
                    </li>
                    <li class="mt-2">
                        <a href="https://github.com/Anduin2017/AnduinOS"
                           class="text-white-50">@Localizer["Source Code"]</a>
                    </li>
                    <li class="mt-2">
                        <a href="https://github.com/Anduin2017/AnduinOS/discussions"
                           class="text-white-50">@Localizer["Community"]</a>
                    </li>
                    <li class="mt-2">
                        <a href="https://docs.anduinos.com/index.html" class="text-white-50">@Localizer["Document"]</a>
                    </li>
                    <li class="mt-2">
                        <a href="https://uptime.aiursoft.com/status/anduinos" class="text-white-50">@Localizer["Service Status"]</a>
                    </li>
                </ul>
            </div>
            <div class="col-12 col-md-4 col-lg-2 mb-3 mb-md-0">
                <h4 class="text-light fs-5">@Localizer["Reference"]</h4>
                <ul class="list-unstyled ps-0 mb-0 mt-3">
                    <li class="mt-2">
                        <a href="https://flathub.org/home" class="text-white-50">Flathub</a>
                    </li>
                    <li class="mt-2">
                        <a href="https://kernel.org/" class="text-white-50">Linux</a>
                    </li>
                    <li class="mt-2">
                        <a href="https://ubuntu.com/desktop" class="text-white-50">Ubuntu</a>
                    </li>
                    <li class="mt-2">
                        <a href="https://www.debian.org/devel/debian-desktop/"
                           class="text-white-50">Debian Desktop</a>
                    </li>
                </ul>
            </div>
            <div class="col-12 col-md-4 col-lg-2 mb-3 mb-md-0">
                <h4 class="text-light fs-5">@Localizer["Legals"]</h4>
                <ul class="list-unstyled ps-0 mb-0 mt-3">
                    <li class="mt-2">
                        <a href="https://github.com/Anduin2017/AnduinOS/blob/1.5/LICENSE"
                           class="text-white-50">@Localizer["License"]</a>
                    </li>
                    <li class="mt-2">
                        <a href="https://github.com/Anduin2017/AnduinOS/blob/1.5/OSS.md"
                           class="text-white-50">@Localizer["Open Source"]</a>
                    </li>
                    <li class="mt-2">
                        <a asp-controller="Home" asp-action="Privacy"
                           class="text-white-50">@Localizer["Privacy Policy"]</a>
                    </li>
                    <li class="mt-2">
                        <a asp-controller="Home" asp-action="Terms"
                           class="text-white-50">@Localizer["Terms of Service"]</a>
                    </li>
                </ul>
            </div>
            <div class="col-12 col-md-4 col-lg-2 mb-3 mb-md-0">
                <h4 class="text-light fs-5">@Localizer["Social"]</h4>
                <ul class="list-unstyled ps-0 mb-0 mt-3">
                    <li class="mt-2">
                        <i class="fa-solid fa-comments"></i>
                        <a href="https://stt.gg/dPwPs8e6" class="text-white-50"
                           target="_blank">Stoat</a>
                    </li>
                    <li class="mt-2">
                        <i class="fa-brands fa-github"></i>
                        <a href="https://github.com/Anduin2017/AnduinOS/" class="text-white-50"
                           target="_blank">Github</a>
                    </li>
                    <li class="mt-2">
                        <i class="fa-brands fa-discord"></i>
                        <a href="https://discord.com/invite/b2N3aB7Ndv" class="text-white-50" rel="me"
                           target="_blank">Discord @Localizer["(Running by community)"]</a>
                    </li>
                    <li class="mt-2">
                        <i class="fa-brands fa-mastodon"></i>
                        <a href="https://mastodon.social/@@AnduinOS" class="text-white-50" rel="me"
                           target="_blank">Mastodon @Localizer["(Running by community)"]</a>
                    </li>
                    <li class="mt-2">
                        <i class="fa-brands fa-reddit"></i>
                        <a href="https://reddit.com/r/AnduinOS/" class="text-white-50" rel="me"
                           target="_blank">Reddit @Localizer["(Running by community)"]</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <p class="text-white-50 mt-4 text-center mb-0">
                    © 2024 - @DateTime.UtcNow.Year <a href="https://anduin.aiursoft.com/" target="_blank">Anduin Xue</a>
                </p>
            </div>
        </div>
    </div>
</footer>